-- ' and " is different in postgres. you need to use ' for string

CREATE DATABASE backend_intro;

-- psql -h localhost -p 5432 -U postgres backend_intro

DROP DATABASE backend_intro;

CREATE TABLE person(
    id INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    gender VARCHAR(6),
    date_of_birth DATE,
    PRIMARY KEY (id) 
);

-- \d to get all table
-- \d table_name to get specific table 
-- \d being "describe"

-- there's no AUTO_INCREMENT in postgres
-- instead it's using SERIAL, SMALLSERIAL, BIGSERIAL
-- or you can use GENERATED AS IDENTITY
-- GENERATED ALWAYS AS IDENTITY
-- GENERATED BY DEFAULT AS IDENTITY

DROP TABLE person;

CREATE TABLE person(
    id BIGSERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender VARCHAR(6) NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(150)
);

INSERT INTO person VALUES(1, 'John', 'Wick', 'MALE', '1988-01-09');

INSERT INTO person(first_name, last_name, gender, date_of_birth) VALUES('John', 'Wick', 'MALE', '1988-01-09');

INSERT INTO person(first_name, last_name, gender, date_of_birth) VALUES('John', 'Wick', 'MALE', '1988-01-09');

INSERT INTO person(first_name, last_name, gender, date_of_birth) VALUES('Natasha', 'Wilona', 'FEMALE', DATE '1990-01-09');


SELECT * FROM person;

INSERT INTO person(first_name, last_name, gender, date_of_birth, email) VALUES('Lana', 'Del', 'Female', '2000-10-05', 'lana@gmail.com');

-- mockaroo is a data generator

ALTER TABLE person ADD country_of_birth VARCHAR(50);

-- \i /c/Users/ASUS/Desktop/Backend-Intro/person.sql

SELECT * FROM person;

SELECT COUNT(id) FROM person;

SELECT * FROM person WHERE id > 850;

SELECT FROM person;

SELECT * FROM person WHERE country_of_birth = 'Indonesia'
ORDER BY first_name DESC;

SELECT DISTINCT country_of_birth
FROM person
ORDER BY country_of_birth;

SELECT *
FROM person
WHERE gender = 'Male' AND (country_of_birth = 'Indonesia' OR country_of_birth = 'China');

SELECT 1<2;

-- LIMIT, OFFSET, PATCH

SELECT * FROM person
LIMIT 10;

-- OFFSET is starting point, offset 5 means you'll get data from 6 onward
SELECT * FROM person OFFSET 5;

-- FETCH are exactly LIMIT no? but worse
-- quick read it said that it's gonne be used in pagination
-- FETCH {FIRST | NEXT} [row_count] {ROW | ROWS} ONLY

SELECT * FROM person OFFSET 5
-- FETCH FIRST 10 ROW ONLY;
FETCH NEXT 10 ROW ONLY;

-- I'm trying FIRST vs NEXT and it's exactly the same hmmm
-- ROW vs ROWS too

SELECT * FROM person
WHERE country_of_birth = 'China' OR
country_of_birth = 'Brazil' OR
country_of_birth = 'France';

SELECT * FROM person
WHERE country_of_birth IN ('China', 'Brazil', 'France');

-- BETWEEN
SELECT * FROM person
WHERE date_of_birth BETWEEN '2000-01-01' AND '2015-01-01';

SELECT * FROM person
WHERE id BETWEEN 10 AND 50;

-- LIKE iLIKE

SELECT * FROM person
WHERE country_of_birth LIKE '%and%';


SELECT * FROM person
WHERE country_of_birth LIKE '%and_';

-- iLIKE are just ignoring upper or lower case
SELECT * FROM person
WHERE country_of_birth iLIKE 'p%';

-- postgres also case sensitive

SELECT country_of_birth, COUNT(*)
-- SELECT COUNT(*)
FROM person
GROUP BY country_of_birth;

-- GROUP BY HAVING
SELECT country_of_birth, COUNT(*)
-- SELECT COUNT(*)
FROM person
GROUP BY country_of_birth
HAVING COUNT(*) > 5;

-- aggregate functions i.e. count, sum, avg, etc

-- \i /Users/ASUS/Desktop/Backend-Intro/car.sql

SELECT MAX(price), MIN(price), AVG(price) FROM car;

SELECT ROUND(AVG(price)) FROM car;

SELECT make, MIN(price), MAX(price), ROUND(AVG(price), 2)
FROM car
GROUP BY make;

SELECT make, model, MIN(price), MAX(price)
FROM car
GROUP BY make, model
ORDER BY make;

SELECT * FROM car
WHERE make = 'Acura' AND model = 'NSX';

SELECT SUM(price) FROM car;

SELECT make, SUM(price)
FROM car
GROUP BY make
ORDER BY SUM(price) DESC;

-- SELECT *, price*.10 AS discount, price-discount AS final_price
SELECT *, price*.10 AS discount, price*0.9 AS final_price
FROM car;

-- COALESCE -> GET FIRST NON-NULL VALUE
SELECT COALESCE(NULL, NULL, 5);

SELECT COALESCE(email, 'Email not provided!') FROM PERSON;

-- NULLIF -> If the 2 parameter is equal, it's value set tO null (?)
-- else it set to first parameter
-- use case only to handle division by zero? sounds not that important tbh

-- TIMESTAMP -> DATE OR TIME
SELECT NOW();

SELECT NOW()::DATE;

SELECT NOW()::TIME;


SELECT NOW() - INTERVAL '1 YEAR';

SELECT NOW() - INTERVAL '10 YEARS';
-- YEARS, MONTHS, DAYS

SELECT NOW()::DATE + INTERVAL '12 DAYS';

SELECT (NOW() + INTERVAL '12 DAYS')::DATE;

SELECT EXTRACT(YEAR FROM NOW());
SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(DOW FROM NOW()); -- DAY OF WEEK

SELECT AGE(date_of_birth)
FROM person
LIMIT 5;

SELECT AGE(NOW(),date_of_birth)
FROM person
LIMIT 5;

SELECT email, COUNT(*) FROM person
GROUP BY email
HAVING COUNT(*) > 1;

-- it's create a constraint named "unique_email_address", i don't think you need it tho
-- nope, you need to name it, otherwise postgres will randomly assign the constraint name
-- which gonna be a hassle later on
ALTER TABLE person ADD CONSTRAINT unique_email_address UNIQUE (email);
-- ALTER TABLE person ADD CONSTRAINT UNIQUE (first_name);
ALTER TABLE person ADD UNIQUE (first_name);

ALTER TABLE person DROP PRIMARY KEY person_pkey;
ALTER TABLE person DROP CONSTRAINT person_pkey;

ALTER TABLE person 
ADD CONSTRAINT aa UNIQUE (id),
ADD CONSTRAINT bb CHECK (id IS NOT NULL);

ALTER TABLE person
DROP CONSTRAINT aa,
DROP CONSTRAINT bb;

ALTER TABLE person ADD CONSTRAINT person_pkey PRIMARY KEY (id);

ALTER TABLE person ADD CONSTRAINT check_gender 
CHECK (gender = 'Male' OR gender = 'Female' OR
        gender = 'MALE' OR gender = 'FEMALE');

SELECT DISTINCT gender FROM person;

SELECT * FROM person
WHERE gender = 'MALE' or gender = 'FEMALE';

SELECT * FROM person WHERE first_name = 'Maxwell';

DELETE FROM person WHERE first_name = 'Maxwell';


insert into person (first_name, last_name, email, gender, date_of_birth, country_of_birth) values ('Wilbert', 'Castro', 'wcastrorr@rakuten.co.jp', 'Female', '2025-10-16', 'Slovenia')
ON CONFLICT (id) DO NOTHING;

ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;
-- EXCLUDED MEANS THE NEW ONE

-- \copy (SELECT * FROM person) TO '/Users/ASUS/Desktop/Backend-Intro/results.csv' DELIMITER ',' CSV HEADER;

SELECT * FROM person_id_seq;

SELECT nextval('person_id_seq'::regclass);

ALTER SEQUENCE person_id_seq RESTART WITH (SELECT COUNT(*) FROM person);

ALTER SEQUENCE person_id_seq RESTART WITH 3;

SELECT COUNT(*) FROM person;

-- EXTENSION
-- SELECT * FROM pg_a;

SELECT * FROM pg_available_extensions;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- \df

SELECT uuid_generate_v4();

CREATE TABLE pet(
    pet_uid UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(100),
    owner_id BIGINT REFERENCES person(id)
);

INSERT INTO pet VALUES(uuid_generate_v4(), 'Blacky', 'Cat');

SELECT * FROM PET;

-- if the column name is equal, you can do it like this
-- SELECT * FROM person
-- JOIN car USING (car_uid)